// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { maybeFilter } from 'bem-ai-mcp/filtering';
import { Metadata, asTextContentResult } from 'bem-ai-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import BemSDK from 'bem-ai';

export const metadata: Metadata = {
  resource: 'tasks',
  operation: 'read',
  tags: [],
  httpMethod: 'get',
  httpPath: '/v1-alpha/tasks',
  operationId: 'listTasks',
};

export const tool: Tool = {
  name: 'list_tasks',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\nList Tasks\n\n# Response Schema\n```json\n{\n  type: 'object',\n  properties: {\n    tasks: {\n      type: 'array',\n      items: {\n        $ref: '#/$defs/task'\n      }\n    },\n    totalCount: {\n      type: 'integer',\n      description: 'The total number of results available.'\n    }\n  },\n  $defs: {\n    task: {\n      type: 'object',\n      properties: {\n        status: {\n          $ref: '#/$defs/task_status'\n        },\n        taskID: {\n          type: 'string',\n          description: 'Unique ID generated by bem following Segment\\'s KSUID conventions.'\n        },\n        type: {\n          type: 'string',\n          description: 'The type of the task.',\n          enum: [            'transformation'\n          ]\n        },\n        createdAt: {\n          type: 'string',\n          description: 'Timestamp when task was initiated.',\n          format: 'date-time'\n        }\n      },\n      required: [        'status',\n        'taskID',\n        'type'\n      ]\n    },\n    task_status: {\n      type: 'string',\n      description: 'The status of the task.',\n      enum: [        'running',\n        'completed',\n        'failed'\n      ]\n    }\n  }\n}\n```",
  inputSchema: {
    type: 'object',
    properties: {
      endingBefore: {
        type: 'string',
        description:
          'A cursor to use in pagination. `endingBefore` is a task ID that defines your place in the list. For example, if you make a list request and receive 50 objects, starting with `tsk_2c9AXIj48cUYJtCuv1gsQtHGDzK`, your subsequent call can include `endingBefore=tsk_2c9AXIj48cUYJtCuv1gsQtHGDzK` to fetch the previous page of the list.\n',
      },
      limit: {
        type: 'integer',
        description: 'This specifies a limit on the number of objects to return, ranging between 1 and 100.',
      },
      sortOrder: {
        type: 'string',
        description:
          'Specifies sorting behavior. The two options are `asc` and `desc` to sort ascending and descending respectively, with default sort being ascending. Paging works in both directions.',
        enum: ['asc', 'desc'],
      },
      startingAfter: {
        type: 'string',
        description:
          'A cursor to use in pagination. `startingAfter` is a task ID that defines your place in the list. For example, if you make a list request and receive 50 objects, ending with `tsk_2c9AXIj48cUYJtCuv1gsQtHGDzK`, your subsequent call can include `startingAfter=tsk_2c9AXIj48cUYJtCuv1gsQtHGDzK` to fetch the next page of the list.\n',
      },
      status: {
        $ref: '#/$defs/task_status',
      },
      taskIDs: {
        type: 'array',
        description: 'Array with the task IDs, formatted as a CSV array.',
        items: {
          type: 'string',
        },
      },
      jq_filter: {
        type: 'string',
        title: 'jq Filter',
        description:
          'A jq filter to apply to the response to include certain fields. Consult the output schema in the tool description to see the fields that are available.\n\nFor example: to include only the `name` field in every object of a results array, you can provide ".results[].name".\n\nFor more information, see the [jq documentation](https://jqlang.org/manual/).',
      },
    },
    required: [],
    $defs: {
      task_status: {
        type: 'string',
        description: 'The status of the task.',
        enum: ['running', 'completed', 'failed'],
      },
    },
  },
};

export const handler = async (client: BemSDK, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  return asTextContentResult(await maybeFilter(args, await client.tasks.list(body)));
};

export default { metadata, tool, handler };
