// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { maybeFilter } from 'bem-ai-mcp/filtering';
import { Metadata, asTextContentResult } from 'bem-ai-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import BemSDK from 'bem-ai';

export const metadata: Metadata = {
  resource: 'tasks',
  operation: 'read',
  tags: [],
  httpMethod: 'get',
  httpPath: '/v1-alpha/tasks/{taskID}',
  operationId: 'getTask',
};

export const tool: Tool = {
  name: 'retrieve_tasks',
  description:
    "When using this tool, always use the `jq_filter` parameter to reduce the response size and improve performance.\n\nOnly omit if you're sure you don't need the data.\n\nGet a Task\n\n# Response Schema\n```json\n{\n  $ref: '#/$defs/task',\n  $defs: {\n    task: {\n      type: 'object',\n      properties: {\n        status: {\n          $ref: '#/$defs/task_status'\n        },\n        taskID: {\n          type: 'string',\n          description: 'Unique ID generated by bem following Segment\\'s KSUID conventions.'\n        },\n        type: {\n          type: 'string',\n          description: 'The type of the task.',\n          enum: [            'transformation'\n          ]\n        },\n        createdAt: {\n          type: 'string',\n          description: 'Timestamp when task was initiated.',\n          format: 'date-time'\n        }\n      },\n      required: [        'status',\n        'taskID',\n        'type'\n      ]\n    },\n    task_status: {\n      type: 'string',\n      description: 'The status of the task.',\n      enum: [        'running',\n        'completed',\n        'failed'\n      ]\n    }\n  }\n}\n```",
  inputSchema: {
    type: 'object',
    properties: {
      taskID: {
        type: 'string',
      },
      jq_filter: {
        type: 'string',
        title: 'jq Filter',
        description:
          'A jq filter to apply to the response to include certain fields. Consult the output schema in the tool description to see the fields that are available.\n\nFor example: to include only the `name` field in every object of a results array, you can provide ".results[].name".\n\nFor more information, see the [jq documentation](https://jqlang.org/manual/).',
      },
    },
    required: ['taskID'],
  },
};

export const handler = async (client: BemSDK, args: Record<string, unknown> | undefined) => {
  const { taskID, ...body } = args as any;
  return asTextContentResult(await maybeFilter(args, await client.tasks.retrieve(taskID)));
};

export default { metadata, tool, handler };
